// This file will be auto-generated by `supabase gen types typescript`
// For now, we provide a minimal placeholder type

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string
          created_at?: string
          updated_at?: string
        }
      }
      groups: {
        Row: {
          id: string
          name: string
          created_by: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          created_by: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_by?: string
          created_at?: string
        }
      }
      group_members: {
        Row: {
          group_id: string
          user_id: string
          role: string
          joined_at: string
        }
        Insert: {
          group_id: string
          user_id: string
          role?: string
          joined_at?: string
        }
        Update: {
          group_id?: string
          user_id?: string
          role?: string
          joined_at?: string
        }
      }
      group_invitations: {
        Row: {
          id: string
          group_id: string
          code: string
          created_by: string
          expires_at: string
          created_at: string
        }
        Insert: {
          id?: string
          group_id: string
          code: string
          created_by: string
          expires_at: string
          created_at?: string
        }
        Update: {
          id?: string
          group_id?: string
          code?: string
          created_by?: string
          expires_at?: string
          created_at?: string
        }
      }
      game_formats: {
        Row: {
          id: string
          name: string
        }
        Insert: {
          id?: string
          name: string
        }
        Update: {
          id?: string
          name?: string
        }
      }
      games: {
        Row: {
          id: string
          group_id: string
          format_id: string
          played_at: string
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          group_id: string
          format_id: string
          played_at?: string
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          group_id?: string
          format_id?: string
          played_at?: string
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      decks: {
        Row: {
          id: string
          group_id: string
          owner_user_id: string | null
          name: string
          colors: string[]
          created_at: string
        }
        Insert: {
          id?: string
          group_id: string
          owner_user_id?: string | null
          name: string
          colors: string[]
          created_at?: string
        }
        Update: {
          id?: string
          group_id?: string
          owner_user_id?: string | null
          name?: string
          colors?: string[]
          created_at?: string
        }
      }
      game_players: {
        Row: {
          game_id: string
          user_id: string
          deck_id: string | null
          deck_name: string | null
          deck_colors: string[]
          commander: string | null
          is_winner: boolean
        }
        Insert: {
          game_id: string
          user_id: string
          deck_id?: string | null
          deck_name?: string | null
          deck_colors?: string[]
          commander?: string | null
          is_winner?: boolean
        }
        Update: {
          game_id?: string
          user_id?: string
          deck_id?: string | null
          deck_name?: string | null
          deck_colors?: string[]
          commander?: string | null
          is_winner?: boolean
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
