/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/verify': RouteRecordInfo<
      '/auth/verify',
      '/auth/verify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/groups/[id]/': RouteRecordInfo<
      '/groups/[id]/',
      '/groups/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/groups/[id]/games/[gameId]': RouteRecordInfo<
      '/groups/[id]/games/[gameId]',
      '/groups/:id/games/:gameId',
      { id: ParamValue<true>, gameId: ParamValue<true> },
      { id: ParamValue<false>, gameId: ParamValue<false> },
      | never
    >,
    '/groups/[id]/games/new': RouteRecordInfo<
      '/groups/[id]/games/new',
      '/groups/:id/games/new',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/groups/[id]/members': RouteRecordInfo<
      '/groups/[id]/members',
      '/groups/:id/members',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/groups/[id]/stats': RouteRecordInfo<
      '/groups/[id]/stats',
      '/groups/:id/stats',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/invite/[code]': RouteRecordInfo<
      '/invite/[code]',
      '/invite/:code',
      { code: ParamValue<true> },
      { code: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile': RouteRecordInfo<
      '/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password': RouteRecordInfo<
      '/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/auth/verify.vue': {
      routes:
        | '/auth/verify'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/groups/[id]/index.vue': {
      routes:
        | '/groups/[id]/'
      views:
        | never
    }
    'src/pages/groups/[id]/games/[gameId].vue': {
      routes:
        | '/groups/[id]/games/[gameId]'
      views:
        | never
    }
    'src/pages/groups/[id]/games/new.vue': {
      routes:
        | '/groups/[id]/games/new'
      views:
        | never
    }
    'src/pages/groups/[id]/members.vue': {
      routes:
        | '/groups/[id]/members'
      views:
        | never
    }
    'src/pages/groups/[id]/stats.vue': {
      routes:
        | '/groups/[id]/stats'
      views:
        | never
    }
    'src/pages/invite/[code].vue': {
      routes:
        | '/invite/[code]'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/profile.vue': {
      routes:
        | '/profile'
      views:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
    }
    'src/pages/reset-password.vue': {
      routes:
        | '/reset-password'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
